### ISSUE TITLE
Can this be done in tflm?

### ISSUE THREAD

**Issue by gamename** [tensorflow/tflite-micro#2478]
Hi,

Background:
I'm using an esp32-s3-eye v2.2. It has 8MB each of flash and PSRAM. Also, esp32-s3-eye chip has an sd card slot. I can use it to load the model file directly (i.e. no need to convert it to a .cc file with xxd. 

Questions: 
  1. Is loading models directly from the sd card a problem in general?
  2. Is it possible to use `yamnet.tflite` on an esp32-s3-eye v2.2 for sound identification? The `yamnet.tflite` file is about 3.9M in size.

Thoughts?

**Comment by ddavis-2015** [comment]
@gamename 

It is not possible to give an exact answer without access to the exact `yamnet.tflite` file you are asking about.  Yamnet is based on mobilenet_v1 so it _should_ be compatible with TFLM.  The size of the model is not an issue as long as you have enough SRAM/PSRAM.  Also TFLM does not care where the model comes from, just that the flatbuffer (.tflite image) exists somewhere in memory.  This can be SRAM/PSRAM/FLASH.  I would suggest moving the model to SRAM/PSRAM as some microcontrollers do not map data access to FLASH memory to their data cache.  The TFLM interpreter uses the flatbuffer for constant tensors (i.e. weights).

You will have to make a guess at the arena size for your application, at first.  Once you get `MicroInterpreter::AllocateTensors()` to not fail due to the arena being too small, you can call `MicroInterpreter::arena_used_bytes()` to get an approximation of the minimum arena size.

**Comment by gamename** [comment]
> @gamename
> 
> It is not possible to give an exact answer without access to the exact `yamnet.tflite` file you are asking about. Yamnet is based on mobilenet_v1 so it _should_ be compatible with TFLM. The size of the model is not an issue as long as you have enough SRAM/PSRAM. Also TFLM does not care where the model comes from, just that the flatbuffer (.tflite image) exists somewhere in memory. This can be SRAM/PSRAM/FLASH. I would suggest moving the model to SRAM/PSRAM as some microcontrollers do not map data access to FLASH memory to their data cache. The TFLM interpreter uses the flatbuffer for constant tensors (i.e. weights).
> 
> You will have to make a guess at the arena size for your application, at first. Once you get `MicroInterpreter::AllocateTensors()` to not fail due to the arena being too small, you can call `MicroInterpreter::arena_used_bytes()` to get an approximation of the minimum arena size.

@ddavis-2015 
Apologies. I should have been clearer.  I was referring to [this](https://www.kaggle.com/models/google/yamnet/frameworks/tfLite) one.

**Comment by gamename** [comment]
> Also TFLM does not care where the model comes from, just that the flatbuffer (.tflite image) exists somewhere in memory.

@ddavis-2015 
Hmm.  Are you saying that no matter how I load the model (from sd card in this case), I have to have an `xxd`-created `.cc` file with the model in hex form?

**Comment by ddavis-2015** [comment]
@gamename 

Unfortunately the model you specified is not compatible with TFLM.  The TFLM interpreter does not support the `Rfft2d` and `ComplexAbs` operations.

**Comment by gamename** [comment]
@ddavis-2015 

What's your thoughts on my other question about the need for a `.cc` file?

**Comment by kirianguiller** [comment]
> @gamename
> 
> Unfortunately the model you specified is not compatible with TFLM. The TFLM interpreter does not support the `Rfft2d` and `ComplexAbs` operations.

I have the same need about using yamnet on an esp32.

Is the fact that Rfft2d and ComplexAbs are not supported by TFLM an incompability with TFLM? Or could the support be added by [following step-by-step documentation](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md)?

Thanks!
