### ISSUE TITLE
Dynamic range quantization support in TFLM

### ISSUE THREAD

**Issue by Doomski99** [tensorflow/tflite-micro#2543]
Hello,

I'm having trouble testing Dynamically quantized models on my DSP simulator. I figured it might be not supported on TFLM. I spent much time searching for an official statement about Dynamic Quantization support for TFLM to no avail. The [PTQ page of tensorflow ](https://www.tensorflow.org/lite/performance/post_training_quantization) summarizes the different quantization options with recommended hardware. But does that also entail "supported hardware" too?

Can I get an official statement about DQ support on TFLM? Does it depend on the chip maker?

Thanks in advance.

**Comment by rascani** [comment]
You are correct that TFLM does not currently support dynamic range quantization. This has primarily been because the microcontrollers we have supported lacked hardware floating point acceleration, so inference performance with DRQ would be poor. We've generally recommended full integer quantization either using PTQ or QAT.

I'm leaving this open for myself to add some documentation to highlight this requirement.
