### ISSUE TITLE
GreedyMemoryPlanner::operator delete(void *) is private

### ISSUE THREAD

**Issue by longhoangth** [tensorflow/tflite-micro#2576]
src/tensorflow/lite/micro/micro_allocator.cpp:390:55: error: 'static void tflite::GreedyMemoryPlanner::operator delete(void*)' is private within this context

**Comment by longhoangth** [comment]
build with [tflite-micro-arduino-examples](https://github.com/tensorflow/tflite-micro-arduino-examples)

**Comment by ddavis-2015** [comment]
@longhoangth 

Can you provide a much more detailed description of your issue?

**Comment by longhoangth** [comment]
When I modify the arduino tensorflow lite library to work with esp32s3 on platformio, the build log error is in image below.
![Screenshot 2024-05-18 133011](https://github.com/tensorflow/tflite-micro/assets/75936654/2413e484-149b-4e58-acf8-97c4b87ada89)

**Comment by rascani** [comment]
This is by design. The `GreedyMemoryPlanner`, like several other TFLM objects, is designed to be allocated from the arena provided to the MicroInterpreter. It is typically allocated here: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/micro_allocator.cc#L88-L90. Notice how it is constructed with placement new.

**Comment by tanmanh0707** [comment]
> When I modify the arduino tensorflow lite library to work with esp32s3 on platformio, the build log error is in image below. ![Screenshot 2024-05-18 133011](https://github.com/tensorflow/tflite-micro/assets/75936654/2413e484-149b-4e58-acf8-97c4b87ada89)

Hello, I run into the same issue. How did you resolve this? Thank you.
