### ISSUE TITLE
MicroProfiler limited to 50 events

### ISSUE THREAD

**Issue by alanvgreen** [tensorflow/tflite-micro#268]
The MicroProfiler is limited to 50 events by the [tflite::MicroProfiler::kMaxEvents](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/micro_profiler.h#L63) constant. This means that for models with more than 50 operations, the profiler is not able to profile the whole model.

Several options:

(a) Do nothing. TfLM users may still modify the constant in micro_profiler.h.
(b) Increase the constant. This will slightly increase TfLM memory footprint, which is not desirable, and the increased value still will not be sufficient for some use cases.
(c) Make the value optionally configurable with a preprocessor #define. Most flexible option, but increases configuration complexity.

**Comment by advaitjain** [comment]
https://github.com/tensorflow/tflite-micro/pull/225 took approach (b) and upped this constant to 1024, so I'll close the current issue.

If this ends up not being a workable solution in the near to mid-term (either because of use-cases that need even more events, or if the additional memory becomes problematic), then we can take an approach similar to the MicroMutableOpResolver and have kMaxEvents be a template parameter that the application can shoose (similar to option (c)):
https://github.com/tensorflow/tflite-micro/blob/1f68a8aacb9aef166e08f02f761f54d7706c1548/tensorflow/lite/micro/micro_mutable_op_resolver.h#L40-L41

In the slightly longer term (and not fully defined at this time), I would like to change the memory management in TFLM to allow allocations like the OpResolver and Profiler to be done from the arena at runtime.

That would give the application / users more control over configuring the model-specific memory requirements.
