### ISSUE TITLE
Rename tflite namespace

### ISSUE THREAD

**Issue by andresovela** [tensorflow/tflite-micro#2683]
On a project I'm working on, we have a dependency both on [tensorflow](https://github.com/tensorflow/tensorflow) and [tflite-micro](https://github.com/tensorflow/tflite-micro).

We recently had an issue due to duplicated namespaces in the workspace, i.e. both tensorflow and tflite-micro use the `tflite` namespace.

As far as I can tell, the implementations under `tensorflow/lite` in the tensorflow and tflite-micro repositories have diverged significantly. I think a rename would be beneficial to avoid clashes and generally much more transparent.

I'd like to propose renaming the `tflite` namespace to `tflm`. The actual name is bikesheddable.

Are there any drawbacks, other than the huge search&replace, to having such a rename in the future?

**Comment by rascani** [comment]
There's still a good chunk of code that is regularly copied from the TFLite repository to TFLM. There is a daily sync of those sources (that is currently broken, but I'm working on that). Since not all of the sources would be able to transition to a tflm namespace, so we'd have to add qualifiers or `using` statements for everything in the `tflm` namespace to use things from the `tflite` namespace.
