### ISSUE TITLE
Add community supported build for ESP32

### ISSUE THREAD

**Issue by mocleiri** [tensorflow/tflite-micro#292]
The CI script already exists to generate the examples and build for esp32.  All that is needed is to copy what is done for the sparkfun edge and create a github action that calls the existing ci script.

Adding this was discussed here in December 2020
https://github.com/tensorflow/tensorflow/pull/45334

**Comment by vikramdattu** [comment]
@mocleiri @advaitjain 

Thanks for adding community build entry!

Examples build for ESP32 are broken currently. I raised a PR few months back on old tensorflow repo, which was pending due to some issues. 
https://github.com/tensorflow/tensorflow/pull/47063 

Will probably pick this again on weekend.
