### ISSUE TITLE
Running quantized nets other than person_detection_int8

### ISSUE THREAD

**Issue by ioannesKX** [tensorflow/tflite-micro#345]
Hello, I'm trying to run quantized mobilenets, other than the default one in the person_detection_int8 example, from https://www.tensorflow.org/lite/guide/hosted_models.

I turn a quantized mobilenet .tflite file I downloaded into a .cc file and replace `lite/micro/tools/make/downloads/person_model_int8/person_detect_model_data.cc` with it. I also tried increased the tensor arena size and changing `model_settings.h` appropriately. I compile and run the binary, but I'm getting this error:
```
tensorflow/lite/micro/kernels/softmax_common.cc:78 input->type != kTfLiteFloat32 (UINT8 != FLOAT32)
Node SOFTMAX (number 30f) failed to prepare with status 1
Type UINT8 (3) not supported.
Node CONV_2D (number 0) failed to invoke with status 1
Invoke failed.
person score:0 no person score 0
```

What am I doing wrong? Or is there another way to run such models in Tflite micro outside the person_detection example perhaps?

**Comment by stanleycelestin1** [comment]
Ensure that your quantization is doing int8 quantization for the entire model (inputs and outputs).

Check this out [Post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization).

**Comment by stanleycelestin1** [comment]
Type UINT8 (3) not supported.  --> is most most likely because you are passing unit8 to the model/interpreter and its expecting a different type. 

```
input = interpreter->input(0);
printf("kTfLiteInt8 ?:  %d\n", input->type);
```

In  https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/c/c_api_types.h you will find: 
`// Types supported by tensor
typedef enum {
  kTfLiteNoType = 0,
  kTfLiteFloat32 = 1,
  kTfLiteInt32 = 2,
  kTfLiteUInt8 = 3,
  kTfLiteInt64 = 4,
  kTfLiteString = 5,
  kTfLiteBool = 6,
  kTfLiteInt16 = 7,
  kTfLiteComplex64 = 8,
  kTfLiteInt8 = 9,
  kTfLiteFloat16 = 10,
  kTfLiteFloat64 = 11,
  kTfLiteComplex128 = 12,
  kTfLiteUInt64 = 13,
  kTfLiteResource = 14,
  kTfLiteVariant = 15,
  kTfLiteUInt32 = 16,
} TfLiteType;`

so check that ` input->type` lines up with what you are inputing.

**Comment by njeffrie** [comment]
+1 Thanks for your help Stanley.

Please do check out the post training quantization link, especially the integer only quantization section.

**Comment by ioannesKX** [comment]
Thanks for your replies.
Is it trivial to transform those models to use int8 instead?
If not, shouldn't https://www.tensorflow.org/lite/guide/hosted_models this page host int8 models instead of those current uint8 ones? Since tflite seems to be dropping support for uint8 overall.

**Comment by njeffrie** [comment]
Unfortunately converting unit8 models to int8 once they are in .tflite form isn't easy - I agree the hosted models should be converted. Those are primarily designed to run on TFLite not TFLM, which has backwards compatibility with uint8.
