### ISSUE TITLE
 kiss_fft.c: No such file or directory

### ISSUE THREAD

**Issue by dfinol** [tensorflow/tflite-micro#550]
When following directions to build the micro_speech example for ESP32 (https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech). I'm getting the following error: 

../components/tfmicro/tensorflow/lite/experimental/microfrontend/lib/kiss_fft_int16.cc:5:10: fatal error: kiss_fft.c: No such file or directory
 #include "kiss_fft.c"

**Comment by advaitjain** [comment]
ESP32 is broken for a few different reasons:
 * https://github.com/tensorflow/tflite-micro/issues/521#issuecomment-924385123
 * https://github.com/tensorflow/tflite-micro/issues/458

Apologies for not having a solution to your issue, but I am going to close this issue since we are not able to support the makefile base project generation moving forward.
