### ISSUE TITLE
flatbuffer::Table - vTable format

### ISSUE THREAD

**Issue by ClaasMeints** [tensorflow/tflite-micro#558]
Hello there,

I am currently working on a solution to get a tflite-micro model working on memory that is split onto different (physical) devices (I am working with C++).
It would be very helpful if I had some information how the vTable (flatbuffers.h - class Table) is stored in the .tflite format. Is there any documentation on the format I couldnt find, or would you mind sending me some examples?

Thanks for your help!

PS: My main problem is to find the head of the vTable

**Comment by petewarden** [comment]
Hi @ClaasMeints! Sorry you're hitting issues. Unfortunately we don't have any additional documentation on the flatbuffer format, the closest thing is this Colab which shows how to use the Python API to manipulate files:

https://colab.research.google.com/drive/11R9hd_0zvW0y3mesitNtF8dCjf27xP9T?usp=sharing

Closing this bug on here, since I think the question might be more suited for the flatbuffers project.
