### ISSUE TITLE
download_and_extract.sh script hitting error on sed

### ISSUE THREAD

**Issue by vikramdattu** [tensorflow/tflite-micro#604]
Working on creating a repo for ESP examples.

With latest sources, I hit below error with sed:

```
+ sed -i '1 i\#ifndef _KISS_FFT_GUTS_H\n#define _KISS_FFT_GUTS_H\n' tensorflow/lite/micro/tools/make/downloads/kissfft/_kiss_fft_guts.h
sed: 1: "tensorflow/lite/micro/t ...": undefined label 'ensorflow/lite/micro/tools/make/downloads/kissfft/_kiss_fft_guts.h'
make: *** [tensorflow/lite/micro/tools/make/Makefile:600: tensorflow/lite/micro/tools/make/downloads/kissfft] Error 1
```

Culprit seem to be below lines of code added few weeks back in `patch_kissfft` function:
```
  sed -i '1 i\#ifndef _KISS_FFT_GUTS_H\n#define _KISS_FFT_GUTS_H\n' tensorflow/lite/micro/tools/make/downloads/kissfft/_kiss_fft_guts.h
  sed -i '$a\#endif // _KISS_FFT_GUTS_H\n' tensorflow/lite/micro/tools/make/downloads/kissfft/_kiss_fft_guts.h

```

cc @shlmregev

**Comment by advaitjain** [comment]
Can you confirm that you are hitting the issue with a fresh checkout (or after running `make clean_downloads`)?

Also, are you attempting on Linux or Windows?

The Linux CI is ok, so I would suspect this to be caused by some corner case not covered by the CI. Full reproduction steps would be very helpful for us to debug this further.
