### ISSUE TITLE
Is it possible to add custom operators in tensorflow lite micro?

### ISSUE THREAD

**Issue by LixiangHan** [tensorflow/tflite-micro#619]
I want to use a custom operator in the framework of tflm, which is not a operator or fused operator of tensorflow. Is it possible? And how to do?

**Comment by QiwenLi0729** [comment]
I have the same question. 
and how I write some options of custom operator to `custom_options` field of `Operator` of flatbuffer ? 

schema_v3b.fbs:
```
table Operator {

  opcode_index:uint;

  // Optional input are indicated by -1.
  inputs:[int];
  outputs:[int];

  builtin_options:BuiltinOptions;
  custom_options:[ubyte];
  custom_options_format:CustomOptionsFormat;

  mutating_variable_inputs:[bool];

  intermediates:[int];
}
```

**Comment by ScholliYT** [comment]
I would also be interested in this. I've got a running TF-Lite model using these converter options. However, this one won't run on TFLM because the FLEX Conv2D Operation is not supported.

```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
#  tf.lite.OpsSet.SELECT_TF_OPS
]
```

I would lilke to implement that layer manually because as far as I know TFLM also does not support `SELECT_TF_OPS`.

![image](https://user-images.githubusercontent.com/12571895/149848286-8f7f2c8c-ab87-4725-974f-06b303589840.png)

**Comment by deqiangc** [comment]
Hello,

Unfortunately, documentation are not quite there. But there is an example code here on custom ops:

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/test_helper_custom_ops.cc
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/test_helper_custom_ops.h

Please take a look at that example and see if that helps.
