### ISSUE TITLE
Data for Unit Tests

### ISSUE THREAD

**Issue by fpedd** [tensorflow/tflite-micro#640]
I am just getting started with TFLM and wanted to extend the unit testing examples with some more test cases (for some internal experiments of mine; I am mainly interested in the CMSIS-NN kernels). However, generating new test data appears harder than I would have thought. To keep things simple I wanted to extend the [add_test.cc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/add_test.cc), specifically the [QuantizedAddNoActivationInt8](https://github.com/tensorflow/tflite-micro/blob/e958bb116195517499033e1295a42e58cf5cf057/tensorflow/lite/micro/kernels/add_test.cc#L223) test. I was planning on adding a couple of extra values to the `input1`, `input2` and `golden` data value arrays. However, when running `ChooseQuantizationParams()` with the already present data values I get vastly different `scaling` and `zero_point` values than the ones present. It appears (pure guessing at this point) as if they are based on some sort of histogram approach, instead of the min/max approach from `ChooseQuantizationParams()`.

What am I doing wrong? Where do those values come from? :)

**Comment by fabianpedd** [comment]
Additionally, I noticed that adding more "random" numbers to the test data leads to the tests failing. This is because the results are sometimes "off by one" due to the quantization. The tests used to account for [that](https://github.com/tensorflow/tensorflow/blob/faa4b423c2cb5a2926e35c80ab7143816409630f/tensorflow/lite/experimental/micro/kernels/add_test.cc#L184) until the validation was moved into a common [ValidateAddGoldens](https://github.com/tensorflow/tflite-micro/blob/e958bb116195517499033e1295a42e58cf5cf057/tensorflow/lite/micro/kernels/add_test.cc#L64) function for both float and integer. The default tolerance for the floats does not account for the off by one error in the quantization case. The values currently used for the tests are never of by one. This is either by pure chance or they are specifically chosen this way. But for example `0.68+2.77= 3.45` will make them fail. What is the reason the "off by one" handling got removed? It is still present in other tests, for example `mul` and `conv`.  Adding a `1` to [here](https://github.com/tensorflow/tflite-micro/blob/e958bb116195517499033e1295a42e58cf5cf057/tensorflow/lite/micro/kernels/add_test.cc#L139), similar to [here](https://github.com/tensorflow/tflite-micro/blob/e958bb116195517499033e1295a42e58cf5cf057/tensorflow/lite/micro/kernels/mul_test.cc#L120) should probably suffice. Thanks
